apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - persistent_volume_claim.yaml
  - role_binding.yaml
  #- service_account.yaml
  #- secret-role.yaml
  # no longer needed after
  # validating https://issues.redhat.com/browse/HACBS-1522
