apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: devfile-sample-python-basic
  annotations:
    pipelinesascode: '1'
    image.redhat.com/generate: 'true'
spec:
  application: simple-python
  componentName: devfile-sample-python-basic
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
  source:
    git:
      context: ./
      devfileUrl: >-
        https://raw.githubusercontent.com/scoheb/devfile-sample-python-basic/main/devfile.yaml
      dockerfileUrl: >-
        https://raw.githubusercontent.com/scoheb/devfile-sample-python-basic/main/docker/Dockerfile
      url: 'https://github.com/scoheb/devfile-sample-python-basic'
  targetPort: 8081

