---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-service-pipeline-rolebinding-dev
  namespace: ralphjbean
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
- kind: ServiceAccount
  name: m7-service-account
  namespace: managed-rbean
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-service-pipeline-rolebinding-managed
  namespace: managed-rbean
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
- kind: ServiceAccount
  name: m7-service-account
  namespace: managed-rbean
